name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0 */3 * * *"
  push:
    branches: 
      - master
      - main
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        run: npm ci
      - name: Update gist
        uses: shadow-lr/waka-box@master  # 原 matchai/waka-box，修改成自己的
        run: node ./index.js  --unhandled-rejections=strict
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 5d02afe2e6daf16ec9ce0e40ab0c328a
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

